### ISSUE TITLE
[Epic]: DX

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#695]
- [ ] local image proxy
- [ ] get dumps for local/initial content
- [ ] show relevant changes on branch switch (migrations/packages/updates/dataset changes)
