### ISSUE TITLE
[Epic]: Harden Authorization

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#732]
- [ ] don't use admin (supabaseClient.setAuth) (e.g. app/storage.server.ts, app/routes/upload/uploadHandler.server.ts, app/routes/upload/delete.server.ts)
- [ ] RLS
- [ ] Fix Broken reset email/password
- [ ] CSRF (sameSite: "lax") [Issue](https://github.com/mint-vernetzt/community-platform/issues/473) see [https://portswigger.net/web-security/csrf/samesite-cookies](https://portswigger.net/web-security/csrf/samesite-cookies)
