### ISSUE TITLE
[Epic]: Deployment

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#742]
- [ ] concept

- [ ] DO Droplet for future prod
- [ ] Check ghcr (limits, howto, security, public)
- [ ] Pipeline (node cache, test, build docker, push, deploy trigger...)

# Orchestration
- [ ] Traefik/SSL/Community Hosting
- [ ] make trigger for deployment
- [ ] make target rollback (nice 2 have)

# Prerequisites
- [ ] droplet with dockerd
- [ ] unattended upgrades
- [ ] firewall
- [ ] able to send emails
- [ ] (reachable with DNS entry)
- [ ] Subdomain for droplet (requires ip first)

# nice2have
- [ ] zero downtime deployment

# must (later)
- [ ] infrastructure as code
- [ ] monitoring

**Comment by nac62116** [comment]
When this is done it potentially closes #365 and #366 
Please correct me if i'm wrong
