### ISSUE TITLE
[Epic]: Infrastructure

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/community-platform#756]
- Create a concept for our infrastructure
- [x] Dockerize Application?
- [ ] Infrastructure as code
- [ ] Multiple providers (Hetzner, Digitalocean, Netlify, AWS, ...) Hetzner Cloud, DomainFactory, PlatformSH, IONOS?
- [x] Misc Droplet for service evaluation
